/**:
  # Global Parameters
  ros__parameters:
    use_sim_time: true
    tf_timeout_threshold: 0.1

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      cmd_freq: 50.0  # Hz of platform commands send

  # State Estimator
  state_estimator:
    ros__parameters:
      plugin_name: "ground_truth"
      base_frame: ""  # Base frame of the robot for gazebo, so it matches the namespace.
      # publish_hz: 100.0  # Set the frequency of the state estimator output.
      ground_truth:
        # Use twist from the simulator instead of default (differentiate the pose).
        twist_sub_topic: "ground_truth/twist"

      # # Ground truth fused with the IMU (simple_ekf)
      # # Might need imu parameters and covariance tuning.
      # plugin_name: "simple_ekf"
      # simple_ekf:
      #   update_topics: ["gt_pose"]
      #   gt_pose:
      #     topic: "ground_truth/pose"
      #     type: "geometry_msgs/msg/PoseStamped"
      #     set_earth_map: true
      #     use_message_covariance: false  # Use the fixed values below, not the message ones.
      #     position_covariance: [1e-4, 1e-4, 1e-4]     # x, y, z — variance, sigma ~ 1 cm
      #     orientation_covariance: [1e-5, 1e-5, 1e-5]  # roll, pitch, yaw — sigma ~ 0.2 deg

  # Motion Controller
  controller_manager:
    ros__parameters:
      cmd_freq: 50.0 # Hz of controller commands send

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      # takeoff_plugin_name: "takeoff_plugin_speed"
      takeoff_plugin_name: "takeoff_plugin_position"
      # takeoff_plugin_name: "takeoff_plugin_trajectory"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_speed"
      # land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
      # go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
      # follow_path_plugin_name: "follow_path_plugin_trajectory"

  # Trajectory Generation Behavior
  TrajectoryGeneratorBehavior:
    ros__parameters:
      plugin_name: "dynamic_mav_trajectory_generator"

  # Behaviors Perception
  point_gimbal_behavior:
    ros__parameters:
      behavior_timeout: 10.0
      gimbal_name: gimbal
      gimbal_frame_id: gimbal/_0/_1/_2
      gimbal_base_frame_id: gimbal
      gimbal_threshold: 0.01